FROM node:18-alpine

# Install OpenSSL and other necessary packages
RUN apk add --no-cache openssl libc6-compat

# Define work directory
WORKDIR /src

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose the port the app runs on
EXPOSE 4000

# Command to run the application with proper debugging
CMD ["npm", "run", "dev"]