#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Exécuter lint-staged dans le dossier client
cd client && npx lint-staged

# Revenir à la racine
cd ..

# Exécuter lint-staged pour les fichiers serveur si nécessaire
cd server && npx lint-staged